<div class="sub_header_in">
    <div class="container">
        <h1>Profil Desa</h1>
    </div>
</div>
<div class="container margin_80_55">
    <h2>Sejarah Singkat Desa Pegiringan</h2> 
    <p>Pegiringan adalah desa di kecamatan Bantarbolang, Pemalang, Jawa Tengah, Indonesia. Pegiringan salah satu desa di kecamatan Bantarbolang yang mempunyai bahasa yang khas di banding daerah lain di Pemalang, yaitu pengucapan vokal akhir (a) dibaca dengan (e) seperti pada kata jebeh, belah, sime dan sebagainya.</p>
    <p>Desa pegiringan tergolong desa yang cukup maju dengan ditunjang akses utama Pemalang – Purwokerto. Roda perekonomian yang semakin pesat dengan banyak dibangunnya infrastruktur perdagangan di jalan-jalan yang menjadi akses utama desa tetangga yaitu desa Wangkaldoyong, Banjarsari dan wanarata.ketiga desa yang berada di belakang desa pegiringan dari akses utama kota. didesa pegiringan itu sendiri terbagi menjadi dua blok besar yaitu blok cokrah dan blok ndukuh,yang masing-masing mempunyai perkembangan yang pesat,dari perekonomian dan pertanian,diantaranya banyaknya dibangunya tempat perdangan yang banyak disebutnya pasar kaget atau pasar janggleng. untuk sarana prasarana seperti TPQ dan Madrasyah Diniyah dan banyak lagi ‘rumah belajar’ yang menyediakan berbagai buku-buku pengetahuan dan keterampilan untuk kalanagan anak-anak yang masih duduk dibangku sekolah banyak didirikan oleh individu maupun yang dari instansi pemerintah.tidak kalah pentingnya usaha para petani selama ini menurut catatan desa kenaikan penghasilan para petani meningkat 75% dari tahun sebelumnya. Disamping faktor alam yang mendukung pemerintah daerah juga ikut peran serta dengan penyuluhan petani setiap sebulan sekali untuk suvey perkembangan dan pengetahuan untuk penanggulangan kegagalan pertanian akibat hama.</p>
    <p>Desa pegiringan tergolong desa yang cukup makmur dengan pertanian dan roda perekonomian,hal tersebut ditunjang oleh kerja keras seluruh masyarakat desa pegiringan yang sebagian besar adalah perantau dijakarta dan sekitarnya,banyak hal yang berkembang didasari oleh permodalan yang tidak sedikit pengorbanan,bermodalkan ketekadan dan kemauan keras untuk mengadu nasib demi menghidupi keluarga dirumah,perantau banyak menciptakan perekonomian baru dengan hasil materi dan ilmu pengalaman dikota rantau. masarakat berlomba-lomba mengembangkan pengelaman kerja untuk ditanamkan di desa pegiringan.tidak kalah pentingnya aset produktif seperti membeli sawah dan kebun dan menanamkan modal kepihak pengusaha-pengusaha kecil didesa pegiringan untuk bagi hasil.menurut catatan survey 40% penduduk desa pegiringan menjadi perantau.</p>
</div>
